// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.32.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.greet(name: name, hint: hint);

String mycelAddressFromSecretKey({required List<int> data, dynamic hint}) =>
    RustLib.instance.api.mycelAddressFromSecretKey(data: data, hint: hint);

Uint8List mycelGenerateSecretKey({dynamic hint}) =>
    RustLib.instance.api.mycelGenerateSecretKey(hint: hint);
