// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.32.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.greet(name: name, hint: hint);

Uint8List generateSecretKey({dynamic hint}) =>
    RustLib.instance.api.generateSecretKey(hint: hint);

String addressFromSecretKey({required List<int> data, dynamic hint}) =>
    RustLib.instance.api.addressFromSecretKey(data: data, hint: hint);

Future<void> startMycelium(
        {required List<String> peers,
        required int tunFd,
        required List<int> privKey,
        dynamic hint}) =>
    RustLib.instance.api.startMycelium(
        peers: peers, tunFd: tunFd, privKey: privKey, hint: hint);
